title: Binary Analysis Cookbook
description: Actionable recipes for disassembling and analyzing binaries for security risks
show_downloads: false
google_analytics: UA-151521702-1
theme: jekyll-theme-slate
