title: Binary Analysis Cookbook
description: Actionable recipes for disassembling and analyzing binaries for security risks
show_downloads: false
google_analytics: G-RJTYMV9KHM
theme: jekyll-theme-slate
